In [53]:
def name(var, namespace):
    return [x for x in namespace if namespace[x] is var][0]

In [65]:
a=4

In [55]:
name(a,globals())

'a'

In [56]:
import pandas as pd
data=pd.read_csv('test.csv')

In [57]:
name(data,globals())

'data'

In [58]:
globals()['a']

4

In [59]:
locals()['a']

4

In [60]:
locals()['a']

4

In [61]:
globals()==locals()

True

In [148]:
def names(dat_name):
    for x in globals():
        if globals()[x] is dat_name:
               return x

In [149]:
dat=data.copy()

In [150]:
b=data

In [151]:
names(b)

'data'

In [138]:
names(dat)

'dat'

In [139]:
names(data)

'data'

In [140]:
names(data)

'data'

In [141]:
globals()['_i112']

"globals()['a']"

In [142]:
globals()['a']

4

In [143]:
globals()['_i118']

"globals()['_i114']"

In [120]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj]',
  'a=4',
  'namestr(a,global)',
  'namestr(a,globals())',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  "import pandas as pd\ndata=read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] == var][0]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "globals()['data']",
  "globals()['a']",
  'globals()',
  'locals()',
  "locals()['data']",
  'name(data,locals())',
  "globals()['a']",
  'name(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'name(data,locals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def name(var, namespace):\n    return x for x in namespace if namespace[x] is var',
  'def name(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:            \n            return x',
  'a=4',
  'name(a,globals())',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def names(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:\n            return x\n        ',
  'names(data,globals())',
  'names(a,globals())',
  'a=4',
  'names(a,globals())',
  'dat=data',
  'names(data,globals())',
  'names(dat,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'names(b,globals())',
  'b=data',
  'names(b,globals())',
  'danames(b,globals())',
  'names(b,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'def names(var):\n    for x in globals():\n        if globals[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b,globals())',
  'names(b)',
  'def names(var):\n    for x in globals():\n        if globals()[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat,globals())',
  'names(dat)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat)',
  'names(psuedo)',
  'names(dat_name)',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            print(x)        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        ##if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'names(data)',
  'globals()',
  'globals',
  'globals()',
  'globals()[data]',
  'globals()[a]',
  "globals()['a']",
  "globals()['_i94']",
  "globals()['_i112']",
  'globals()',
  "globals('i114')",
  "globals('_i114')",
  "globals()['_i114']",
  "globals()['_i118']",
  'globals()'],
 '_oh': {4: ['a'],
  7: 'a',
  11: 'data',
  14: 'a',
  18: 'a',
  20: 'data',
  22: 'data',
  28: 'a',
  29:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  30: 4,
  31: {...},
  32: {...},
  33:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  34: '_',
  35: 4,
  36: '___',
  38: 'data',
  39: 'data',
  40: 4,
  41: 4,
  42: 4,
  43: True,
  47: '__',
  49: '___',
  52: ['a', '_30', '_35', '_40', '_41', '_42'],
  55: 'a',
  57: 'data',
  58: 4,
  59: 4,
  60: 4,
  61: True,
  63: 'data',
  64: '___',
  66: 'a',
  68: 'data',
  69: 'data',
  71: 'dat',
  74: 'data',
  76: 'data',
  78: 'dat',
  87: 'data',
  89: 'dat',
  93: 'data',
  94: 'dat',
  97: 'data',
  103: 'data',
  105: '__name__',
  106: '__name__',
  107: {...},
  108: <function globals()>,
  109: {...},
  112: 4,
  113: 'names(dat)',
  114: "globals()['a']",
  115: {...},
  118: "globals()['_i112']",
  119: "globals()['_i114']"},
 '_dh': ['C:\\Users\\INT171'],
 'In': ['',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj]',
  'a=4',
  'namestr(a,global)',
  'namestr(a,globals())',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  "import pandas as pd\ndata=read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] == var][0]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "globals()['data']",
  "globals()['a']",
  'globals()',
  'locals()',
  "locals()['data']",
  'name(data,locals())',
  "globals()['a']",
  'name(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'name(data,locals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def name(var, namespace):\n    return x for x in namespace if namespace[x] is var',
  'def name(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:            \n            return x',
  'a=4',
  'name(a,globals())',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def names(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:\n            return x\n        ',
  'names(data,globals())',
  'names(a,globals())',
  'a=4',
  'names(a,globals())',
  'dat=data',
  'names(data,globals())',
  'names(dat,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'names(b,globals())',
  'b=data',
  'names(b,globals())',
  'danames(b,globals())',
  'names(b,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'def names(var):\n    for x in globals():\n        if globals[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b,globals())',
  'names(b)',
  'def names(var):\n    for x in globals():\n        if globals()[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat,globals())',
  'names(dat)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat)',
  'names(psuedo)',
  'names(dat_name)',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            print(x)        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        ##if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'names(data)',
  'globals()',
  'globals',
  'globals()',
  'globals()[data]',
  'globals()[a]',
  "globals()['a']",
  "globals()['_i94']",
  "globals()['_i112']",
  'globals()',
  "globals('i114')",
  "globals('_i114')",
  "globals()['_i114']",
  "globals()['_i118']",
  'globals()'],
 'Out': {4: ['a'],
  7: 'a',
  11: 'data',
  14: 'a',
  18: 'a',
  20: 'data',
  22: 'data',
  28: 'a',
  29:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  30: 4,
  31: {...},
  32: {...},
  33:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...

In [124]:
names_locals

NameError: name 'names_locals' is not defined

In [125]:
vars()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj]',
  'a=4',
  'namestr(a,global)',
  'namestr(a,globals())',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  "import pandas as pd\ndata=read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] == var][0]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "globals()['data']",
  "globals()['a']",
  'globals()',
  'locals()',
  "locals()['data']",
  'name(data,locals())',
  "globals()['a']",
  'name(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'name(data,locals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def name(var, namespace):\n    return x for x in namespace if namespace[x] is var',
  'def name(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:            \n            return x',
  'a=4',
  'name(a,globals())',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def names(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:\n            return x\n        ',
  'names(data,globals())',
  'names(a,globals())',
  'a=4',
  'names(a,globals())',
  'dat=data',
  'names(data,globals())',
  'names(dat,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'names(b,globals())',
  'b=data',
  'names(b,globals())',
  'danames(b,globals())',
  'names(b,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'def names(var):\n    for x in globals():\n        if globals[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b,globals())',
  'names(b)',
  'def names(var):\n    for x in globals():\n        if globals()[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat,globals())',
  'names(dat)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat)',
  'names(psuedo)',
  'names(dat_name)',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            print(x)        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        ##if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'names(data)',
  'globals()',
  'globals',
  'globals()',
  'globals()[data]',
  'globals()[a]',
  "globals()['a']",
  "globals()['_i94']",
  "globals()['_i112']",
  'globals()',
  "globals('i114')",
  "globals('_i114')",
  "globals()['_i114']",
  "globals()['_i118']",
  'globals()',
  'names_locals()',
  'names.locals()',
  'names.locals',
  'names_locals',
  'vars()'],
 '_oh': {4: ['a'],
  7: 'a',
  11: 'data',
  14: 'a',
  18: 'a',
  20: 'data',
  22: 'data',
  28: 'a',
  29:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  30: 4,
  31: {...},
  32: {...},
  33:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  34: '_',
  35: 4,
  36: '___',
  38: 'data',
  39: 'data',
  40: 4,
  41: 4,
  42: 4,
  43: True,
  47: '__',
  49: '___',
  52: ['a', '_30', '_35', '_40', '_41', '_42'],
  55: 'a',
  57: 'data',
  58: 4,
  59: 4,
  60: 4,
  61: True,
  63: 'data',
  64: '___',
  66: 'a',
  68: 'data',
  69: 'data',
  71: 'dat',
  74: 'data',
  76: 'data',
  78: 'dat',
  87: 'data',
  89: 'dat',
  93: 'data',
  94: 'dat',
  97: 'data',
  103: 'data',
  105: '__name__',
  106: '__name__',
  107: {...},
  108: <function globals()>,
  109: {...},
  112: 4,
  113: 'names(dat)',
  114: "globals()['a']",
  115: {...},
  118: "globals()['_i112']",
  119: "globals()['_i114']",
  120: {...}},
 '_dh': ['C:\\Users\\INT171'],
 'In': ['',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj]',
  'a=4',
  'namestr(a,global)',
  'namestr(a,globals())',
  'def namestr(obj, namespace):\n    return [name for name in namespace if namespace[name] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  "import pandas as pd\ndata=read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test')",
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is obj][0]',
  'a=4',
  'namestr(a,globals())',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'namestr(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] == var][0]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "globals()['data']",
  "globals()['a']",
  'globals()',
  'locals()',
  "locals()['data']",
  'name(data,locals())',
  "globals()['a']",
  'name(data,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  'name(data,locals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def name(var, namespace):\n    return x for x in namespace if namespace[x] is var',
  'def name(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:            \n            return x',
  'a=4',
  'name(a,globals())',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var]',
  'a=4',
  'name(a,globals())',
  'def name(var, namespace):\n    return [x for x in namespace if namespace[x] is var][0]',
  'a=4',
  'name(a,globals())',
  "import pandas as pd\ndata=pd.read_csv('test.csv')",
  'name(data,globals())',
  "globals()['a']",
  "locals()['a']",
  "locals()['a']",
  'globals()==locals()',
  'def names(var, namespace):\n    for x in namespace:\n        if namespace[x] is var:\n            return x\n        ',
  'names(data,globals())',
  'names(a,globals())',
  'a=4',
  'names(a,globals())',
  'dat=data',
  'names(data,globals())',
  'names(dat,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'names(b,globals())',
  'b=data',
  'names(b,globals())',
  'danames(b,globals())',
  'names(b,globals())',
  'dat=data.copy()',
  'names(dat,globals())',
  'def names(var):\n    for x in globals():\n        if globals[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b,globals())',
  'names(b)',
  'def names(var):\n    for x in globals():\n        if globals()[x] is var:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat,globals())',
  'names(dat)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'names(dat)',
  'names(psuedo)',
  'names(dat_name)',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            print(x)        ',
  'dat=data.copy()',
  'b=data',
  'names(b)',
  'def names(dat_name):\n    for x in globals():\n        if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'def names(dat_name):\n    for x in globals():\n        ##if globals()[x] is dat_name:\n            return x        ',
  'names(data)',
  'names(data)',
  'globals()',
  'globals',
  'globals()',
  'globals()[data]',
  'globals()[a]',
  "globals()['a']",
  "globals()['_i94']",
  "globals()['_i112']",
  'globals()',
  "globals('i114')",
  "globals('_i114')",
  "globals()['_i114']",
  "globals()['_i118']",
  'globals()',
  'names_locals()',
  'names.locals()',
  'names.locals',
  'names_locals',
  'vars()'],
 'Out': {4: ['a'],
  7: 'a',
  11: 'data',
  14: 'a',
  18: 'a',
  20: 'data',
  22: 'data',
  28: 'a',
  29:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0
  3          0.12     0.00   564.533      0.0      0.0      4.0      NaN      1
  4          2.47     0.00  4289.020      0.0      1.0      3.0      1.0      1
  ...         ...      ...       ...      ...      ...      ...      ...    ...
  29995     34.46     0.50   419.953      1.0      3.0      3.0      0.0      0
  29996      0.29     0.67  6239.070      1.0      2.0      6.0      0.0      1
  29997     37.23     0.00    37.230      0.0      0.0      2.0      0.0      0
  29998 -22364.60     1.00  9004.100      1.0     12.0      3.0      1.0      0
  29999      0.00     0.00  2231.460      0.0      7.0      3.0      NaN      0

  [30000 rows x 113 columns],
  30: 4,
  31: {...},
  32: {...},
  33:           var_1      var_9      var_7     var_5     var_8     var_17  \
  0       29330.0        NaN        NaN  2853.690       NaN        NaN
  1        1260.0     511.64     511.64    84.000    511.64     511.64
  2        7834.0   13042.30   10453.10  2611.330   8057.08   16886.50
  3       38036.0   11503.90    4168.97   683.621   3963.56   10132.70
  4       12004.5    4990.14    8516.47   291.064   6366.47    7487.02
  ...         ...        ...        ...       ...       ...        ...
  29995   24881.0   21834.10   22879.50  1074.150  21171.60   21834.10
  29996   86716.0   13838.70   14401.40  1716.000   7676.37   14275.30
  29997   19664.0    2397.89    2397.89   655.467   2397.89    2397.89
  29998  116560.0  149337.00  193224.00  2438.560  99847.10  151229.00
  29999   13712.0    3245.22    3504.00   920.329   3496.00    6367.96

            var_3      var_6    var_16     var_10  ...   var_155     var_264  \
  0      1629.440  4882.9700  3334.830  146489.00  ...  1.616670         NaN
  1        84.000    14.0000    84.000        NaN  ...  0.083333     2.64000
  2      2611.330    87.0444  2611.330    2611.33  ...  0.016667    74.67800
  3       528.278  1564.7300   693.439   70413.00  ...  1.177780   564.53300
  4       187.571   278.1280   540.354   12515.80  ...  0.494444  4289.02000
  ...         ...        ...       ...        ...  ...       ...         ...
  29995   857.966   668.3600  1074.150   20050.80  ...  0.311111   419.95300
  29996  1421.570  2230.8000  2102.590   66924.00  ...  1.177780     2.76846
  29997   655.467   218.4890   655.467   19664.00  ...  0.166667    37.23000
  29998  2241.530  3982.9800  3211.380  119489.00  ...  1.411110  9004.10000
  29999   761.778   357.9060   899.681   10737.20  ...  0.200000  2231.46000

          var_259  var_287   var_252  var_286  var_266  var_262  var_301  event
  0           NaN     1.00       NaN      1.0      3.0      2.0      NaN      0
  1          2.64     0.00     2.640      0.0      1.0      1.0      NaN      0
  2          2.08     0.00   472.256      0.0     21.0      4.0      NaN      0

In [127]:
vars()['data'] is data

True